# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "ko-KR"
reviews:
  profile: "assertive" # 깐깐하게 로직 검토
  request_changes_workflow: false # AI가 승인을 막지 않도록 설정
  high_level_summary: true
  review_status: true
  review_details: false
  poem: false # 불필요한 기능 제거
  pre_merge_checks:
    docstrings:
      mode: "off"
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - "develop"
      - "main"
chat:
  auto_reply: true
