spring:
  application:
    name: GACHI-BE
  profiles:
    default: dev
  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

app:
  s3:
    region: ${AWS_REGION:ap-northeast-2}
    bucket: ${AWS_S3_BUCKET:}
    public-base-url: ${AWS_S3_PUBLIC_BASE_URL:}
    image-prefix: ${AWS_S3_IMAGE_PREFIX:images}
