spring:
  application:
    name: GACHI-BE
  profiles:
    default: dev
  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false