spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/gachi}
    username: ${DB_USERNAME:gachi}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  packages-to-scan: com.gachi.be
  paths-to-match: /api/**

app:
  auth:
    email:
      noop-allowed: true
