package com.gachi.be.global.code;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;

@Getter
@RequiredArgsConstructor
public enum SuccessCode {
  OK(HttpStatus.OK, "OK200", "요청에 성공하였습니다."),
  CREATED(HttpStatus.CREATED, "OK201", "생성에 성공하였습니다."),
  AUTH_SIGNUP_SUCCESS(HttpStatus.CREATED, "AUTH2011", "회원가입이 완료되었습니다."),
  AUTH_LOGIN_SUCCESS(HttpStatus.OK, "AUTH2001", "로그인에 성공하였습니다."),
  AUTH_REISSUE_SUCCESS(HttpStatus.OK, "AUTH2002", "토큰 재발급에 성공하였습니다."),
  AUTH_EMAIL_CODE_SENT(HttpStatus.OK, "AUTH2003", "이메일 인증 코드가 발송되었습니다."),
  AUTH_EMAIL_VERIFIED(HttpStatus.OK, "AUTH2004", "이메일 인증이 완료되었습니다."),
  AUTH_CHECK_LOGIN_ID_AVAILABLE(HttpStatus.OK, "AUTH2005", "사용 가능한 아이디입니다."),
  AUTH_CHECK_EMAIL_AVAILABLE(HttpStatus.OK, "AUTH2006", "사용 가능한 이메일입니다."),
  AUTH_CHECK_PHONE_NUMBER_AVAILABLE(HttpStatus.OK, "AUTH2007", "사용 가능한 전화번호입니다."),
  AUTH_FIND_LOGIN_ID_EMAIL_CODE_SENT(HttpStatus.OK, "AUTH2008", "아이디 찾기 인증 코드가 발송되었습니다."),
  AUTH_FIND_LOGIN_ID_SUCCESS(HttpStatus.OK, "AUTH2009", "아이디 찾기에 성공하였습니다."),
  AUTH_PASSWORD_RESET_EMAIL_CODE_SENT(HttpStatus.OK, "AUTH2010", "비밀번호 재설정 인증 코드가 발송되었습니다."),
  AUTH_PASSWORD_RESET_EMAIL_VERIFIED(HttpStatus.OK, "AUTH2012", "비밀번호 재설정 이메일 인증이 완료되었습니다."),
  AUTH_PASSWORD_RESET_SUCCESS(HttpStatus.OK, "AUTH2013", "비밀번호 재설정이 완료되었습니다."),
  AUTH_LOGOUT_SUCCESS(HttpStatus.OK, "AUTH2014", "로그아웃에 성공하였습니다."),
  CHILD_CREATE_SUCCESS(HttpStatus.CREATED, "CHILD2011", "자녀 정보 등록에 성공하였습니다."),
  CHILD_GET_LIST_SUCCESS(HttpStatus.OK, "CHILD2001", "내 자녀 목록 조회에 성공하였습니다."),
  CHILD_UPDATE_SUCCESS(HttpStatus.OK, "CHILD2002", "자녀 정보 수정에 성공하였습니다."),
  CHILD_DELETE_SUCCESS(HttpStatus.OK, "CHILD2003", "자녀 삭제에 성공하였습니다."),
  SCHOOL_SEARCH_SUCCESS(HttpStatus.OK, "SCH2001", "학교 검색 결과 조회에 성공하였습니다."),
  SCHOOL_CLASS_LIST_SUCCESS(HttpStatus.OK, "SCH2002", "학교 반 목록 조회에 성공하였습니다."),
  SCHOOL_GUIDE_CATEGORY_SUCCESS(HttpStatus.OK, "SG2001", "카테고리별 FAQ 개수 조회에 성공하였습니다."),
  SCHOOL_GUIDE_POPULAR_SUCCESS(HttpStatus.OK, "SG2002", "주간 인기 질문 조회에 성공하였습니다."),
  SCHOOL_GUIDE_LIST_SUCCESS(HttpStatus.OK, "SG2003", "FAQ 목록 조회에 성공하였습니다."),
  SCHOOL_GUIDE_DETAIL_SUCCESS(HttpStatus.OK, "SG2004", "FAQ 상세 조회에 성공하였습니다."),
  SCHOOL_GUIDE_CREATE_SUCCESS(HttpStatus.CREATED, "SG2011", "FAQ 등록에 성공하였습니다."),
  SCHOOL_GUIDE_UPDATE_SUCCESS(HttpStatus.OK, "SG2005", "FAQ 수정에 성공하였습니다."),
  SCHOOL_GUIDE_DELETE_SUCCESS(HttpStatus.OK, "SG2006", "FAQ 삭제에 성공하였습니다."),
  NEWSLETTER_UPLOAD_SUCCESS(HttpStatus.CREATED, "NL2011", "업로드가 시작되었습니다."),
  NEWSLETTER_RETRY_ACCEPTED(HttpStatus.ACCEPTED, "NL2021", "가정통신문 분석 재시도가 시작되었습니다."),
  NEWSLETTER_STATUS_SUCCESS(HttpStatus.OK, "NL2001", "요청에 성공하였습니다."),
  NEWSLETTER_TRANSLATION_SUCCESS(HttpStatus.OK, "NL2002", "번역 결과 조회에 성공하였습니다."),
  NEWSLETTER_SUMMARY_SUCCESS(HttpStatus.OK, "NL2003", "요약 결과 조회에 성공하였습니다."),
  NEWSLETTER_CHECKLIST_SUCCESS(HttpStatus.OK, "NL2004", "체크리스트 조회에 성공하였습니다."),
  NEWSLETTER_DETAIL_SUCCESS(HttpStatus.OK, "NL2005", "가정통신문 상세 조회에 성공하였습니다."),
  NEWSLETTER_LIST_SUCCESS(HttpStatus.OK, "NL2006", "가정통신문 목록 조회에 성공하였습니다."),
  NEWSLETTER_RECENT_SUCCESS(HttpStatus.OK, "NL2007", "최근 가정통신문 조회에 성공하였습니다."),
  NEWSLETTER_CONVERSATION_TOPICS_SUCCESS(HttpStatus.OK, "NL2008", "대화 주제 조회에 성공하였습니다."),
  NEWSLETTER_CULTURAL_GUIDES_SUCCESS(HttpStatus.OK, "NL2009", "문화 맥락 안내 조회에 성공하였습니다."),
  CALENDAR_PREVIEW_SUCCESS(HttpStatus.OK, "CAL2001", "캘린더 일정 미리보기 조회에 성공하였습니다."),
  CALENDAR_PREVIEW_MOCK_SUCCESS(HttpStatus.OK, "CAL2000", "캘린더 미리보기 더미 데이터가 Redis에 주입되었습니다."),
  CALENDAR_DATES_UPDATED(HttpStatus.OK, "CAL2002", "일정 날짜 수정에 성공하였습니다."),
  CALENDAR_REGISTER_SUCCESS(HttpStatus.CREATED, "CAL2011", "캘린더 일정 등록에 성공하였습니다."),
  CALENDAR_MONTHLY_SUCCESS(HttpStatus.OK, "CAL2003", "월별 캘린더 마커 조회에 성공하였습니다."),
  CALENDAR_WEEKLY_SUCCESS(HttpStatus.OK, "CAL2004", "주별 캘린더 조회에 성공하였습니다."),
  CALENDAR_DAILY_SUCCESS(HttpStatus.OK, "CAL2005", "날짜별 캘린더 조회에 성공하였습니다."),
  CALENDAR_SCHOOL_SCHEDULE_SUCCESS(HttpStatus.OK, "CAL2006", "자녀 학교 학사일정 조회에 성공하였습니다."),
  CALENDAR_SCHOOL_MEAL_SUCCESS(HttpStatus.OK, "CAL2007", "자녀 학교 급식표 조회에 성공하였습니다."),
  CALENDAR_ELEMENTARY_TIMETABLE_SUCCESS(HttpStatus.OK, "CAL2008", "자녀 학교 시간표 조회에 성공하였습니다."),
  CHECKLIST_TODAY_SUCCESS(HttpStatus.OK, "CL2001", "오늘 마감 체크리스트 조회에 성공하였습니다."),
  CHECKLIST_COMPLETE_SUCCESS(HttpStatus.OK, "CL2002", "체크리스트 완료 처리에 성공하였습니다."),
  CHECKLIST_DELETED(HttpStatus.OK, "CL2003", "체크리스트 삭제에 성공하였습니다."),
  USER_LANGUAGE_UPDATED(HttpStatus.OK, "USER2001", "언어 설정이 변경되었습니다."),
  USER_NOTIFICATION_UPDATED(HttpStatus.OK, "USER2002", "알림 설정이 변경되었습니다."),
  USER_PROFILE_UPDATED(HttpStatus.OK, "USER2003", "프로필 정보가 변경되었습니다."),
  USER_EMAIL_CHANGE_CODE_SENT(HttpStatus.OK, "USER2004", "이메일 변경 인증 코드가 발송되었습니다."),
  USER_EMAIL_CHANGE_VERIFIED(HttpStatus.OK, "USER2005", "이메일 변경 인증이 완료되었습니다."),
  USER_EMAIL_UPDATED(HttpStatus.OK, "USER2006", "이메일이 변경되었습니다."),
  USER_PASSWORD_UPDATED(HttpStatus.OK, "USER2007", "비밀번호가 변경되었습니다."),
  USER_WITHDRAWAL_SUCCESS(HttpStatus.OK, "USER2008", "회원 탈퇴가 완료되었습니다."),
  NOTIFICATION_LIST_SUCCESS(HttpStatus.OK, "NOTI2001", "알림 목록 조회에 성공하였습니다."),
  NOTIFICATION_UNREAD_COUNT_SUCCESS(HttpStatus.OK, "NOTI2002", "미읽음 알림 수 조회에 성공하였습니다."),
  NOTIFICATION_READ_SUCCESS(HttpStatus.OK, "NOTI2003", "알림 읽음 처리에 성공하였습니다."),
  NOTIFICATION_PUSH_TOKEN_REGISTERED(HttpStatus.OK, "NOTI2004", "푸시 토큰 등록에 성공하였습니다."),
  NOTIFICATION_PUSH_TOKEN_DELETED(HttpStatus.OK, "NOTI2005", "푸시 토큰 삭제에 성공하였습니다."),
  CHAT_MESSAGE_SUCCESS(HttpStatus.OK, "CHAT2001", "채팅 응답에 성공하였습니다.");

  private final HttpStatus httpStatus;
  private final String code;
  private final String message;
}
