CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    type VARCHAR(40) NOT NULL,
    title VARCHAR(120) NOT NULL,
    body TEXT NOT NULL,
    payload_json TEXT NULL,
    dedupe_key VARCHAR(255) NULL,
    read_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notifications_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT chk_notifications_type
        CHECK (type IN ('NEWSLETTER_ANALYSIS','CALENDAR_EVENT','CHECKLIST_DUE','SYSTEM','ANNOUNCEMENT'))
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_id_id
    ON notifications (user_id, id DESC);

CREATE INDEX IF NOT EXISTS idx_notifications_user_unread
    ON notifications (user_id, id DESC)
    WHERE read_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_notifications_user_dedupe_key
    ON notifications (user_id, dedupe_key)
    WHERE dedupe_key IS NOT NULL;

CREATE TABLE IF NOT EXISTS push_device_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    platform VARCHAR(20) NOT NULL,
    token VARCHAR(512) NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    device_id VARCHAR(128) NULL,
    app_version VARCHAR(50) NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    last_registered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_push_device_tokens_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT chk_push_device_tokens_platform
        CHECK (platform IN ('IOS','ANDROID','EXPO')),
    CONSTRAINT uk_push_device_tokens_user_token_hash
        UNIQUE (user_id, token_hash)
);

CREATE INDEX IF NOT EXISTS idx_push_device_tokens_user_active
    ON push_device_tokens (user_id, enabled, deleted_at);

CREATE INDEX IF NOT EXISTS idx_push_device_tokens_device_id
    ON push_device_tokens (user_id, device_id)
    WHERE device_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS notification_delivery_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id BIGINT NOT NULL,
    push_device_token_id BIGINT NULL,
    status VARCHAR(20) NOT NULL,
    provider_message_id VARCHAR(255) NULL,
    failure_reason TEXT NULL,
    attempted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notification_delivery_logs_notification
        FOREIGN KEY (notification_id) REFERENCES notifications (id) ON DELETE CASCADE,
    CONSTRAINT fk_notification_delivery_logs_push_device_token
        FOREIGN KEY (push_device_token_id) REFERENCES push_device_tokens (id) ON DELETE SET NULL,
    CONSTRAINT chk_notification_delivery_logs_status
        CHECK (status IN ('PENDING','SENT','FAILED','SKIPPED'))
);

CREATE INDEX IF NOT EXISTS idx_notification_delivery_logs_notification
    ON notification_delivery_logs (notification_id, attempted_at DESC);

CREATE INDEX IF NOT EXISTS idx_notification_delivery_logs_status
    ON notification_delivery_logs (status, attempted_at DESC);
