CREATE TABLE IF NOT EXISTS conversation_topics (
                                                   id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                   newsletter_id BIGINT      NOT NULL,
                                                   user_id       BIGINT      NOT NULL,
                                                   topic         TEXT        NOT NULL,
                                                   created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                   updated_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                                   CONSTRAINT fk_conversation_topic_newsletter
                                                   FOREIGN KEY (newsletter_id) REFERENCES newsletter (id) ON DELETE CASCADE
    );

CREATE INDEX IF NOT EXISTS idx_conversation_topics_newsletter_id
    ON conversation_topics (newsletter_id);
