CREATE TABLE IF NOT EXISTS school_guide (
                                            id                 BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            category           VARCHAR(50) NOT NULL,
    question           TEXT        NOT NULL,
    answer             TEXT        NOT NULL,
    weekly_view_count  BIGINT      NOT NULL DEFAULT 0,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

CREATE INDEX IF NOT EXISTS idx_school_guide_category
    ON school_guide (category);

CREATE INDEX IF NOT EXISTS idx_school_guide_weekly_view_count
    ON school_guide (weekly_view_count DESC);
