-- 가정통신문 ↔ 학교 생활 가이드(FAQ) 매핑 테이블.
-- AI가 스캔 시점에 선정한 FAQ의 id만 저장한다.
-- 질문/답변 본문은 school_guide 테이블의 question_i18n / answer_i18n을 그대로 사용하므로
-- 여기에 텍스트를 복사 저장하지 않는다. (재번역 불필요 + 원문 정확도 보장)
CREATE TABLE IF NOT EXISTS newsletter_cultural_guides (
                                                          id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                          newsletter_id   BIGINT      NOT NULL,  -- FK → newsletter
                                                          user_id         BIGINT      NOT NULL,  -- FK → users
                                                          school_guide_id BIGINT      NOT NULL,  -- FK → school_guide
                                                          display_order   INT         NOT NULL DEFAULT 0,  -- AI가 반환한 순서 (0부터)
                                                          created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                          updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_newsletter_cultural_guides_newsletter_id
    ON newsletter_cultural_guides (newsletter_id);

-- 재분석 시 중복 저장 방지 (WHERE 절 없는 일반 유니크 인덱스 → H2 호환)
CREATE UNIQUE INDEX IF NOT EXISTS uq_newsletter_cultural_guides_pair
    ON newsletter_cultural_guides (newsletter_id, school_guide_id);
