CREATE TABLE IF NOT EXISTS social_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider VARCHAR(20) NOT NULL,
    provider_user_id VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_social_accounts_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_social_accounts_provider_user
        UNIQUE (provider, provider_user_id),
    CONSTRAINT uk_social_accounts_user_provider
        UNIQUE (user_id, provider),
    CONSTRAINT chk_social_accounts_provider
        CHECK (provider IN ('KAKAO'))
);

CREATE INDEX IF NOT EXISTS idx_social_accounts_user_id
    ON social_accounts (user_id);

-- 소셜 로그인 회원은 서비스 전용 아이디/비밀번호/전화번호가 없을 수 있다.
ALTER TABLE users ALTER COLUMN login_id DROP NOT NULL;
ALTER TABLE users ALTER COLUMN password_hash DROP NOT NULL;
ALTER TABLE users ALTER COLUMN phone_number DROP NOT NULL;
