ALTER TABLE social_accounts
    ADD COLUMN connection_status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE social_accounts
    ADD CONSTRAINT chk_social_accounts_connection_status
        CHECK (connection_status IN ('ACTIVE', 'DISCONNECT_PENDING'));

CREATE TABLE kakao_unlink_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider_user_id VARCHAR(100) NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMP WITH TIME ZONE,
    last_error VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_kakao_unlink_outbox_pending_provider_user
    ON kakao_unlink_outbox (provider_user_id)
    WHERE processed_at IS NULL;

CREATE INDEX idx_kakao_unlink_outbox_due
    ON kakao_unlink_outbox (next_attempt_at, id)
    WHERE processed_at IS NULL;
