ALTER TABLE newsletter
DROP CONSTRAINT IF EXISTS chk_newsletter_status;

ALTER TABLE newsletter
    ADD CONSTRAINT chk_newsletter_status
        CHECK (status IN ('PENDING', 'PROCESSING', 'PAUSED', 'COMPLETED', 'FAILED'));

--  newsletter 문서 단위 페이지 메타데이터 + 멈춤 상태
--    source_type : PDF / IMAGE (기존 레코드는 NULL → 파일 확장자로 판단)
--    total_pages : 전체 페이지 수 (PDF는 클로바 OCR 응답 후 확정)
--    paused_*    : PAUSED 상태일 때 어느 페이지가 어떤 단계/사유로 멈췄는지
--    paused_at   : 24시간 방치 시 자동 FAILED 처리 기준 시각
ALTER TABLE newsletter
    ADD COLUMN IF NOT EXISTS source_type VARCHAR(10) NULL;

ALTER TABLE newsletter
    ADD COLUMN IF NOT EXISTS total_pages INTEGER NULL;

ALTER TABLE newsletter
    ADD COLUMN IF NOT EXISTS paused_page_no INTEGER NULL;

ALTER TABLE newsletter
    ADD COLUMN IF NOT EXISTS paused_stage VARCHAR(20) NULL;

ALTER TABLE newsletter
    ADD COLUMN IF NOT EXISTS paused_reason VARCHAR(30) NULL;

ALTER TABLE newsletter
    ADD COLUMN IF NOT EXISTS paused_at TIMESTAMPTZ NULL;

-- 24시간 방치 문서 정리 스케줄러가 PAUSED 문서만 빠르게 찾도록 Partial Index
CREATE INDEX IF NOT EXISTS idx_newsletter_paused_at
    ON newsletter (paused_at)
    WHERE status = 'PAUSED';

--  페이지 단위 결과 테이블
--    file_key         : 이미지는 해당 장의 원본 키, PDF는 모든 페이지가 같은 PDF 키
--    display_file_key : 이미지 화면 표시/OCR/AI 첨부용 키. EXIF 회전이 있으면 보정 JPEG 키, 없으면 원본 키. PDF는 NULL
--    image_width/height : display_file_key 이미지의 픽셀 크기 (오버레이 비율 계산용). PDF는 NULL
--    retry_count      : 현재 실패 사유로 사용자가 '다시 시도'를 누른 횟수 (버튼 노출 규칙 계산용)
--    blocks           : 이미지 오버레이용 문단/블록 목록 (원문/번역/0~1 비율 좌표). PDF는 NULL
CREATE TABLE IF NOT EXISTS newsletter_page (
                                               id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               newsletter_id     BIGINT       NOT NULL,
                                               page_no           INTEGER      NOT NULL,
                                               file_key          VARCHAR(500) NOT NULL,
    display_file_key  VARCHAR(500) NULL,
    image_width       INTEGER      NULL,
    image_height      INTEGER      NULL,
    status            VARCHAR(30)  NOT NULL DEFAULT 'PENDING',
    retry_count       INTEGER      NOT NULL DEFAULT 0,
    ocr_text          TEXT         NULL,
    original_text     TEXT         NULL,
    translated_text   TEXT         NULL,
    blocks            JSONB        NULL,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_newsletter_page_newsletter
    FOREIGN KEY (newsletter_id) REFERENCES newsletter (id) ON DELETE CASCADE,
    CONSTRAINT uq_newsletter_page UNIQUE (newsletter_id, page_no),
    CONSTRAINT chk_newsletter_page_status
    CHECK (status IN (
           'PENDING', 'OCR_DONE', 'SUCCESS',
           'OCR_FAILED', 'UNREADABLE', 'TRANSLATION_FAILED', 'SKIPPED'
                     ))
    );
