ALTER TABLE users RENAME COLUMN nickname TO name;

ALTER TABLE users ADD COLUMN login_id VARCHAR(50);
ALTER TABLE users ADD COLUMN password_hash VARCHAR(255);
ALTER TABLE users ADD COLUMN phone_number VARCHAR(20);
ALTER TABLE users ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE users ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE users ADD COLUMN email_verified_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE users ADD COLUMN consent_agreed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE users ADD COLUMN consent_version VARCHAR(20);
ALTER TABLE users ADD COLUMN password_updated_at TIMESTAMP WITH TIME ZONE;

UPDATE users
SET login_id = CONCAT('legacy_', id),
    password_hash = '$2a$10$7EqJtq98hPqEX7fNZaFWoO.jkFKv3x6A2kZZgwyXR0YJIUKGwEuK.',
    phone_number = CONCAT('LEGACY-', id),
    consent_agreed_at = created_at,
    consent_version = 'legacy',
    password_updated_at = created_at
WHERE login_id IS NULL
   OR password_hash IS NULL
   OR phone_number IS NULL
   OR consent_agreed_at IS NULL
   OR consent_version IS NULL
   OR password_updated_at IS NULL;

ALTER TABLE users ALTER COLUMN login_id SET NOT NULL;
ALTER TABLE users ALTER COLUMN password_hash SET NOT NULL;
ALTER TABLE users ALTER COLUMN phone_number SET NOT NULL;
ALTER TABLE users ALTER COLUMN consent_agreed_at SET NOT NULL;
ALTER TABLE users ALTER COLUMN consent_version SET NOT NULL;
ALTER TABLE users ALTER COLUMN password_updated_at SET NOT NULL;

ALTER TABLE users
    ADD CONSTRAINT chk_users_status
        CHECK (status IN ('ACTIVE', 'WITHDRAWN'));

ALTER TABLE users
    ADD CONSTRAINT uk_users_login_id UNIQUE (login_id);

ALTER TABLE users
    ADD CONSTRAINT uk_users_phone_number UNIQUE (phone_number);

CREATE INDEX IF NOT EXISTS idx_users_login_id ON users (login_id);
CREATE INDEX IF NOT EXISTS idx_users_phone_number ON users (phone_number);
CREATE INDEX IF NOT EXISTS idx_users_status_deleted_at ON users (status, deleted_at);

CREATE TABLE IF NOT EXISTS auth_refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    jti VARCHAR(36) NOT NULL,
    device_info VARCHAR(255),
    ip_address VARCHAR(45),
    remember_me BOOLEAN NOT NULL DEFAULT FALSE,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_used_at TIMESTAMP WITH TIME ZONE,
    revoked_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_auth_refresh_tokens_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_auth_refresh_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT uk_auth_refresh_tokens_jti UNIQUE (jti)
);

CREATE INDEX IF NOT EXISTS idx_auth_refresh_tokens_user_revoked
    ON auth_refresh_tokens (user_id, revoked_at);
CREATE INDEX IF NOT EXISTS idx_auth_refresh_tokens_expires_at
    ON auth_refresh_tokens (expires_at);
