CREATE TABLE IF NOT EXISTS children (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    school_name VARCHAR(120) NOT NULL,
    school_code VARCHAR(64),
    grade INTEGER NOT NULL,
    color_code VARCHAR(7) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_children_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT chk_children_grade
        CHECK (grade BETWEEN 1 AND 6)
);

CREATE INDEX IF NOT EXISTS idx_children_user_created_at
    ON children (user_id, created_at);
