CREATE TABLE IF NOT EXISTS checklist_items (
                                               id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               newsletter_id BIGINT       NOT NULL,
                                               content       VARCHAR(500) NOT NULL,
    detail        VARCHAR(500) NULL,
    is_checked    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_checklist_newsletter
    FOREIGN KEY (newsletter_id) REFERENCES newsletter (id) ON DELETE CASCADE
    );

CREATE INDEX IF NOT EXISTS idx_checklist_items_newsletter_id
    ON checklist_items (newsletter_id);

CREATE TABLE IF NOT EXISTS todo_items (
                                          id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          newsletter_id     BIGINT       NOT NULL,
                                          content           VARCHAR(500) NOT NULL,
    target_date       DATE         NULL,
    target_date_label VARCHAR(50)  NULL,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_todo_newsletter
    FOREIGN KEY (newsletter_id) REFERENCES newsletter (id) ON DELETE CASCADE
    );

CREATE INDEX IF NOT EXISTS idx_todo_items_newsletter_id
    ON todo_items (newsletter_id);

CREATE INDEX IF NOT EXISTS idx_todo_items_target_date
    ON todo_items (target_date)
    WHERE target_date IS NOT NULL;
