-- newsletter 테이블 + children 테이블 생성

CREATE TABLE IF NOT EXISTS children (
                                        id             BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        user_id        BIGINT      NOT NULL,
                                        school_id      BIGINT      NULL,
                                        name           VARCHAR(50) NOT NULL,
    birth_date     DATE        NOT NULL,
    grade          INTEGER     NULL,
    class_no       INTEGER     NULL,
    calendar_color VARCHAR(7)  NOT NULL DEFAULT '#000000',
    created_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at     TIMESTAMPTZ NULL,

    CONSTRAINT fk_children_user
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );

CREATE INDEX IF NOT EXISTS idx_children_user_id
    ON children (user_id)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS newsletter (
                                          id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          user_id          BIGINT       NOT NULL,
                                          child_name       VARCHAR(50)  NULL,
    child_grade      INTEGER      NULL,
    child_color      VARCHAR(7)   NULL,
    file_key         VARCHAR(500) NOT NULL,
    file_hash        VARCHAR(64)  NOT NULL,
    status           VARCHAR(20)  NOT NULL DEFAULT 'PENDING'
    CONSTRAINT chk_newsletter_status
    CHECK (status IN ('PENDING','PROCESSING','COMPLETED','FAILED')),
    is_saved         BOOLEAN      NOT NULL DEFAULT FALSE,
    ocr_text         TEXT         NULL,
    original_text    TEXT         NULL,
    translated_text  TEXT         NULL,
    title            VARCHAR(255) NULL,
    summary          TEXT         NULL,
    language         VARCHAR(10)  NOT NULL DEFAULT 'KO',
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_newsletter_user
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );

CREATE UNIQUE INDEX IF NOT EXISTS uq_newsletter_child
    ON newsletter (user_id, child_name, file_hash)
    WHERE child_name IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_newsletter_no_child
    ON newsletter (user_id, file_hash)
    WHERE child_name IS NULL;

CREATE INDEX IF NOT EXISTS idx_newsletter_user_id
    ON newsletter (user_id);

CREATE INDEX IF NOT EXISTS idx_newsletter_user_saved
    ON newsletter (user_id, is_saved);

CREATE INDEX IF NOT EXISTS idx_newsletter_child_name
    ON newsletter (user_id, child_name)
    WHERE child_name IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_newsletter_status
    ON newsletter (status);
