
-- deleted_at 컬럼 추가 (ALTER) + newsletter 테이블 생성

-- null = 활성 자녀, not null = 삭제된 자녀 (Soft Delete)
ALTER TABLE children
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL;

-- deleted_at 기반 인덱스 추가
-- 활성 자녀만 조회하는 쿼리 최적화 (Partial Index)
CREATE INDEX IF NOT EXISTS idx_children_user_active
    ON children (user_id, created_at)
    WHERE deleted_at IS NULL;

-- newsletter 테이블 생성
CREATE TABLE IF NOT EXISTS newsletter (
                                          id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          user_id          BIGINT       NOT NULL,
                                          child_name       VARCHAR(50)  NULL,
    child_grade      INTEGER      NULL,
    child_color      VARCHAR(7)   NULL,
    file_key         VARCHAR(500) NOT NULL,
    file_hash        VARCHAR(64)  NOT NULL,
    status           VARCHAR(20)  NOT NULL DEFAULT 'PENDING'
    CONSTRAINT chk_newsletter_status
    CHECK (status IN ('PENDING','PROCESSING','COMPLETED','FAILED')),
    is_saved         BOOLEAN      NOT NULL DEFAULT FALSE,
    ocr_text         TEXT         NULL,
    original_text    TEXT         NULL,
    translated_text  TEXT         NULL,
    title            VARCHAR(255) NULL,
    summary          TEXT         NULL,
    language         VARCHAR(10)  NOT NULL DEFAULT 'KO',
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_newsletter_user
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );

-- 중복 방지 Partial Unique Index
CREATE UNIQUE INDEX IF NOT EXISTS uq_newsletter_child
    ON newsletter (user_id, child_name, file_hash)
    WHERE child_name IS NOT NULL;

-- 자녀 미선택인 경우: (user_id, file_hash) 조합으로 중복 판단
CREATE UNIQUE INDEX IF NOT EXISTS uq_newsletter_no_child
    ON newsletter (user_id, file_hash)
    WHERE child_name IS NULL;

CREATE INDEX IF NOT EXISTS idx_newsletter_user_id
    ON newsletter (user_id);

-- 홈/목록 화면 쿼리 최적화 (is_saved=true 인 것만 노출하므로)
CREATE INDEX IF NOT EXISTS idx_newsletter_user_saved
    ON newsletter (user_id, is_saved);

CREATE INDEX IF NOT EXISTS idx_newsletter_child_name
    ON newsletter (user_id, child_name)
    WHERE child_name IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_newsletter_status
    ON newsletter (status);
