-- checklist 통합 테이블
CREATE TABLE IF NOT EXISTS checklist (
                                         id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         newsletter_id     BIGINT       NOT NULL,
                                         user_id           BIGINT       NOT NULL,
                                         type              VARCHAR(10)  NOT NULL
    CONSTRAINT chk_checklist_type CHECK (type IN ('CHECKLIST', 'TODO')),
    content           VARCHAR(500) NOT NULL,
    detail            VARCHAR(500) NULL,
    is_completed      BOOLEAN      NOT NULL DEFAULT FALSE,
    target_date       DATE         NULL,
    target_date_label VARCHAR(50)  NULL,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_checklist_newsletter
    FOREIGN KEY (newsletter_id) REFERENCES newsletter (id) ON DELETE CASCADE
    );

CREATE INDEX IF NOT EXISTS idx_checklist_newsletter_id
    ON checklist (newsletter_id);

CREATE INDEX IF NOT EXISTS idx_checklist_user_type_completed
    ON checklist (user_id, type, is_completed);
