CREATE TABLE IF NOT EXISTS calendar_events (
                                               id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               user_id       BIGINT       NOT NULL,
                                               newsletter_id BIGINT       NOT NULL,
                                               child_name    VARCHAR(50)  NULL,
    child_color   VARCHAR(7)   NULL,
    title         VARCHAR(200) NOT NULL,
    description   TEXT         NULL,
    external_key  VARCHAR(255) NULL,
    start_at      TIMESTAMPTZ  NOT NULL,
    end_at        TIMESTAMPTZ  NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_calendar_event_newsletter
    FOREIGN KEY (newsletter_id) REFERENCES newsletter (id) ON DELETE CASCADE,

    CONSTRAINT uq_calendar_event_external_key
    UNIQUE (external_key)
    );

CREATE INDEX IF NOT EXISTS idx_calendar_events_user_start_at
    ON calendar_events (user_id, start_at);

CREATE INDEX IF NOT EXISTS idx_calendar_events_newsletter_id
    ON calendar_events (newsletter_id);

CREATE INDEX IF NOT EXISTS idx_calendar_events_user_child
    ON calendar_events (user_id, child_name)
    WHERE child_name IS NOT NULL;

ALTER TABLE checklist
    ADD COLUMN IF NOT EXISTS calendar_event_id BIGINT NULL;

ALTER TABLE checklist
    ADD CONSTRAINT fk_checklist_calendar_event
        FOREIGN KEY (calendar_event_id)
            REFERENCES calendar_events (id)
            ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_checklist_calendar_event_id
    ON checklist (calendar_event_id)
    WHERE calendar_event_id IS NOT NULL;
